export const languageOptions = [
    { value: 'af', label: 'Afrikaans' },
    { value: 'am', label: 'Amharic' },
    { value: 'ar', label: 'Arabic' },
    { value: 'az', label: 'Azerbaijani' },
    { value: 'be', label: 'Belarusian' },
    { value: 'bg', label: 'Bulgarian' },
    { value: 'bn', label: 'Bengali' },
    { value: 'bs', label: 'Bosnian' },
    { value: 'ca', label: 'Catalan' },
    { value: 'ceb', label: 'Cebuano' },
    { value: 'cs', label: 'Czech' },
    { value: 'cy', label: 'Welsh' },
    { value: 'da', label: 'Danish' },
    { value: 'de', label: 'German' },
    { value: 'el', label: 'Greek' },
    { value: 'en', label: 'English' },
    { value: 'eo', label: 'Esperanto' },
    { value: 'es', label: 'Spanish' },
    { value: 'et', label: 'Estonian' },
    { value: 'eu', label: 'Basque' },
    { value: 'fa', label: 'Persian' },
    { value: 'fi', label: 'Finnish' },
    { value: 'fil', label: 'Filipino' },
    { value: 'fr', label: 'French' },
    { value: 'fy', label: 'Frisian' },
    { value: 'ga', label: 'Irish' },
    { value: 'gd', label: 'Scots Gaelic' },
    { value: 'gl', label: 'Galician' },
    { value: 'gu', label: 'Gujarati' },
    { value: 'ha', label: 'Hausa' },
    { value: 'haw', label: 'Hawaiian' },
    { value: 'he', label: 'Hebrew' },
    { value: 'hi', label: 'Hindi' },
    { value: 'hmn', label: 'Hmong' },
    { value: 'hr', label: 'Croatian' },
    { value: 'ht', label: 'Haitian Creole' },
    { value: 'hu', label: 'Hungarian' },
    { value: 'hy', label: 'Armenian' },
    { value: 'id', label: 'Indonesian' },
    { value: 'ig', label: 'Igbo' },
    { value: 'is', label: 'Icelandic' },
    { value: 'it', label: 'Italian' },
    { value: 'ja', label: 'Japanese' },
    { value: 'jw', label: 'Javanese' },
    { value: 'ka', label: 'Georgian' },
    { value: 'kk', label: 'Kazakh' },
    { value: 'km', label: 'Khmer' },
    { value: 'kn', label: 'Kannada' },
    { value: 'ko', label: 'Korean' },
    { value: 'ku', label: 'Kurdish (Kurmanji)' },
    { value: 'ky', label: 'Kyrgyz' },
    { value: 'la', label: 'Latin' },
    { value: 'lb', label: 'Luxembourgish' },
    { value: 'lo', label: 'Lao' },
    { value: 'lt', label: 'Lithuanian' },
    { value: 'lv', label: 'Latvian' },
    { value: 'mg', label: 'Malagasy' },
    { value: 'mi', label: 'Maori' },
    { value: 'mk', label: 'Macedonian' },
    { value: 'ml', label: 'Malayalam' },
    { value: 'mn', label: 'Mongolian' },
    { value: 'mr', label: 'Marathi' },
    { value: 'ms', label: 'Malay' },
    { value: 'mt', label: 'Maltese' },
    { value: 'my', label: 'Myanmar (Burmese)' },
    { value: 'ne', label: 'Nepali' },
    { value: 'nl', label: 'Dutch' },
    { value: 'no', label: 'Norwegian' },
    { value: 'ny', label: 'Chichewa' },
    { value: 'pa', label: 'Punjabi' },
    { value: 'pl', label: 'Polish' },
    { value: 'ps', label: 'Pashto' },
    { value: 'pt', label: 'Portuguese' },
    { value: 'ro', label: 'Romanian' },
    { value: 'ru', label: 'Russian' },
    { value: 'sd', label: 'Sindhi' },
    { value: 'si', label: 'Sinhala' },
    { value: 'sk', label: 'Slovak' },
    { value: 'sl', label: 'Slovenian' },
    { value: 'sm', label: 'Samoan' },
    { value: 'sn', label: 'Shona' },
    { value: 'so', label: 'Somali' },
    { value: 'sq', label: 'Albanian' },
    { value: 'sr', label: 'Serbian' },
    { value: 'st', label: 'Sesotho' },
    { value: 'su', label: 'Sundanese' },
    { value: 'sv', label: 'Swedish' },
    { value: 'sw', label: 'Swahili' },
    { value: 'ta', label: 'Tamil' },
    { value: 'te', label: 'Telugu' },
    { value: 'tg', label: 'Tajik' },
    { value: 'th', label: 'Thai' },
    { value: 'tl', label: 'Tagalog' },
    { value: 'tr', label: 'Turkish' },
    { value: 'uk', label: 'Ukrainian' },
    { value: 'ur', label: 'Urdu' },
    { value: 'uz', label: 'Uzbek' },
    { value: 'vi', label: 'Vietnamese' },
    { value: 'xh', label: 'Xhosa' },
    { value: 'yi', label: 'Yiddish' },
    { value: 'yo', label: 'Yoruba' },
    { value: 'zu', label: 'Zulu' },
];

export  const categories = [
    { id: 0, name: "General Text", icon: "📝" },
    { id: 1, name: "Website", icon: "🌐" },
    { id: 2, name: "Software/IT", icon: "💻" },
    { id: 3, name: "Travel", icon: "✈️" },
    { id: 4, name: "Legal", icon: "📜" },
    { id: 5, name: "Business/Finance", icon: "💰" },
    { id: 6, name: "Marketing / Media", icon: "📣" },
    { id: 7, name: "Medicine / Healthcare", icon: "💊" },
    { id: 8, name: "Art / Music", icon: "🎵" },
    { id: 9, name: "Gaming / Video Games", icon: "🎮" },
    { id: 10, name: "Engineering / Technical", icon: "🎓" },
    { id: 11, name: "Education / Learning", icon: "📚" },
    { id: 12, name: "Food / Catering", icon: "🍽️" },
    { id: 13, name: "Fashion / Lifestyle", icon: "👤" }
]
